Feature/feature/selection selectors
zeixcom/ueli pull request #29
Opened 2021-11-10 16:15 UTC by tschuems

2021-11-10 17:22 UTC, slavanga requested changes

2021-11-10 17:22 UTC, slavanga commented on scss/05-components/_selection.scss
> -  &:not(:only-child) {
Only-child wurde an dieser Stelle verwendet, um Selections ohne Label zu ermöglichen. Diese waren aber immer ohne Custom Style. Lass uns mal besprechen, ob und wie wir das abbilden wollen.

Bootstrap Referenz:
https://getbootstrap.com/docs/5.1/forms/checks-radios/#without-labels

2021-11-10 17:22 UTC, slavanga commented on scss/05-components/_selection.scss
> +  [type='checkbox']:focus ~ label::before {
Die ```:focus```, ```:active```, und ```:checked``` States nicht im Selector mit Radio und Checkbox zusammen nesten. Sonst entstehen im CSS Output unmögliche Kombinationen wie:

.**radio** [type=**checkbox**]:checked ~ label::before

2021-11-10 17:22 UTC, slavanga commented on scss/05-components/_selection.scss
> +    font-weight: inherit;
Bitte noch den  lint Command ```npm run lint``` ausführen, damit die Property Order angepasst wird 😉

2021-11-10 17:22 UTC, slavanga commented on dist/ueli.css
>    top: 0.25em;
Da jetzt unterschiedliche Sizes für Radio Buttons und Checkboxen möglich sind, brauchen wir auch separate top offsets:
- $radio-offset-top
- $checkbox-offset-top

2021-11-11 09:39 UTC, tschuems commented on scss/05-components/_selection.scss
> +  [type='checkbox']:focus ~ label::before {
habe hier jetzt einfach `input` anstatt dem attribute selector genommen

2021-11-11 09:52 UTC, slavanga commented on scss/05-components/_selection.scss
> +    top: $radio-offset-top;
Hier ```$checkbox-offset-top``` verwenden

2021-11-11 09:52 UTC, slavanga commented on scss/00-settings/_variables.scss
> +$radio-offset-top: to-em(4px) !default;
```suggestion
$radio-offset-top: to-em(3px) !default;
```

2021-11-11 09:54 UTC, tschuems commented on scss/05-components/_selection.scss
> +    top: $radio-offset-top;
ui schlampig :see_no_evil:

2021-11-11 09:59 UTC, slavanga approved these changes

2021-11-11 10:09 UTC, merged