rename format and make code clearer
zeixcom/ueli pull request #41
Opened 2022-05-11 17:03 UTC by flicksolutions

2022-05-12 14:57 UTC, slavanga requested changes
@flicksolutions LGTM! Bitte noch die Texte korrigieren. `package-lock.json` wurde mit einer alten npm version generiert. Das ist daran erkennbar, dass die lockfileVersion auf 1 geändert wurde.

Folgende Commands sollten das beheben:
1. `nvm use 14.17.5`
3. `npm i npm -g`
3. `npm i`

2022-05-12 14:57 UTC, slavanga commented on test/modular-scale-config.spec.scss
> +  @include describe('Given a fixed base, exponent and size') {
```suggestion
  @include describe('Given an exponent, a fixed size and a fixed base') {
```

2022-05-12 14:57 UTC, slavanga commented on test/modular-scale-config.spec.scss
> +    'Given a exponent, a breakpoint map with a fluid value size and a fluid value base'
Bei den drei neuen tests auch "an exponent" schreiben

2022-05-13 07:09 UTC, flicksolutions commented
> @flicksolutions LGTM! Bitte noch die Texte korrigieren. `package-lock.json` wurde mit einer alten npm version generiert. Das ist daran erkennbar, dass die lockfileVersion auf 1 geändert wurde.
> 
> Folgende Commands sollten das beheben:
> 
>     1. `nvm use 14.17.5`
> 
>     2. `npm i npm -g`
> 
>     3. `npm i`

hmm... Die lockfile-version wurde vom Workflow verändert! Nicht von mir!
Ich schau mal, ob sich die npm-Version noch separat einstellen lässt...

2022-05-13 09:43 UTC, flicksolutions commented
@slavanga Habe das workflow-file auch in diesen branch gemerged, damit es keine fehlerhaften commits mehr gibt...
Alle anderen Änderungen habe ich versucht zu machen. :-)

2022-05-16 09:24 UTC, slavanga approved these changes

2022-05-16 09:45 UTC, merged